logging:
  level:
    org:
      springframework:
        web: info
#    root: debug
server:
  forward-headers-strategy: framework
  port: 53021
  servlet:
    context-path: /order
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    protocol_header: x-forwarded-proto
    remote_ip_header: x-forwarded-for
spring:
  application:
    name: order-service
  freemarker:
    charset: UTF-8
    content-type: text/html
    enabled: true
    request-context-attribute: rc
    suffix: .html
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false